# -------------------------------------------------------------------
# MIT License
#
# Copyright (c) 2025 Jeremiah Michael Cole Meyer (@jmeyer1980)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction...
# THE SOFTWARE IS PROVIDED "AS IS"...
# -------------------------------------------------------------------
# doctrine-version: 2025.10.12

[ranges]
1B = 8100-8299
4B = 8300-8499
7B = 8500-8699
15B = 8700-8899