# vLLM-Doctrine Comprehensive Test Runner (PowerShell)
# 
# This script orchestrates the complete testing suite for validating
# the vLLM-Doctrine system across all model tiers and scenarios.

param(
    [switch]$ConfigOnly,
    [switch]$ApiOnly,
    [switch]$IdeOnly,
    [switch]$Help
)

$ErrorActionPreference = "Stop"

Write-Host "🧪 vLLM-Doctrine Comprehensive Test Suite" -ForegroundColor Blue
Write-Host "===========================================" -ForegroundColor Blue
Write-Host ""

# Test results tracking
$script:TestsPassed = 0
$script:TestsFailed = 0
$script:TestResults = @()

function Write-Info {
    param($Message)
    Write-Host "ℹ️  $Message" -ForegroundColor Blue
}

function Write-Success {
    param($Message)
    Write-Host "✅ $Message" -ForegroundColor Green
    $script:TestsPassed++
    $script:TestResults += "✅ $Message"
}

function Write-Warning {
    param($Message)
    Write-Host "⚠️  $Message" -ForegroundColor Yellow
}

function Write-Error {
    param($Message)
    Write-Host "❌ $Message" -ForegroundColor Red
    $script:TestsFailed++
    $script:TestResults += "❌ $Message"
}

function Test-Prerequisites {
    Write-Info "Checking prerequisites..."
    
    # Check if we're in the right directory
    if (-not (Test-Path "./initial-bootstrap.sh")) {
        Write-Error "Not in vLLM-Doctrine directory or setup incomplete"
        return $false
    }
    
    # Check Node.js and npm
    try {
        $nodeVersion = node --version 2>$null
        if (-not $nodeVersion) {
            Write-Error "Node.js is required but not installed"
            return $false
        }
    } catch {
        Write-Error "Node.js is required but not installed"
        return $false
    }
    
    try {
        $npmVersion = npm --version 2>$null
        if (-not $npmVersion) {
            Write-Error "npm is required but not installed"
            return $false
        }
    } catch {
        Write-Error "npm is required but not installed"
        return $false
    }
    
    # Install dependencies if needed
    if (-not (Test-Path "node_modules")) {
        Write-Info "Installing test dependencies..."
        npm install
    }
    
    # Check Playwright
    if (-not (Test-Path "node_modules/@playwright")) {
        Write-Error "Playwright not installed - run 'npm install' first"
        return $false
    }
    
    Write-Success "Prerequisites check completed"
    return $true
}

function Initialize-TestEnvironment {
    Write-Info "Setting up test environment..."
    
    # Create test results directory
    if (-not (Test-Path "test-results")) {
        New-Item -ItemType Directory -Path "test-results" -Force | Out-Null
    }
    
    # Stop any running models (this will be handled in WSL if needed)
    Write-Info "Stopping any running models..."
    
    Write-Success "Test environment ready"
}

function Invoke-TestSuite {
    param(
        [string]$SuiteName,
        [string]$TestFile,
        [int]$TimeoutSeconds = 300
    )
    
    Write-Info "Running $SuiteName..."
    
    try {
        $process = Start-Process -FilePath "npx" -ArgumentList "playwright", "test", $TestFile, "--reporter=line" -PassThru -NoNewWindow -Wait
        
        if ($process.ExitCode -eq 0) {
            Write-Success "$SuiteName completed"
            return $true
        } else {
            Write-Error "$SuiteName failed with exit code $($process.ExitCode)"
            return $false
        }
    } catch {
        Write-Error "$SuiteName failed with error: $($_.Exception.Message)"
        return $false
    }
}

function New-TestReport {
    $reportFile = "test-results/comprehensive-test-report.md"
    
    $content = @"
# vLLM-Doctrine Comprehensive Test Report

**Generated:** $(Get-Date)
**Total Tests:** $($script:TestsPassed + $script:TestsFailed)
**Passed:** $script:TestsPassed
**Failed:** $script:TestsFailed
**Success Rate:** $(if (($script:TestsPassed + $script:TestsFailed) -gt 0) { [math]::Round(($script:TestsPassed * 100 / ($script:TestsPassed + $script:TestsFailed)), 2) } else { 0 })%

## Test Results

$($script:TestResults -join "`n")

## Environment Information

- **OS:** $($env:OS) $($env:PROCESSOR_ARCHITECTURE)
- **Date:** $(Get-Date)
- **Node.js:** $(try { node --version } catch { "Not available" })
- **Python:** $(try { python3 --version } catch { "Not available" })
- **PowerShell:** $($PSVersionTable.PSVersion)

## Notes

This report was generated by the vLLM-Doctrine comprehensive test suite.
For detailed test outputs, check the individual test result files in the test-results directory.
"@

    Set-Content -Path $reportFile -Value $content
    Write-Success "Test report generated: $reportFile"
}

function Show-Help {
    Write-Host "vLLM-Doctrine Comprehensive Test Runner"
    Write-Host ""
    Write-Host "Usage: .\run-comprehensive-tests.ps1 [options]"
    Write-Host ""
    Write-Host "Options:"
    Write-Host "  -Help          Show this help message"
    Write-Host "  -ConfigOnly    Run only configuration tests"
    Write-Host "  -ApiOnly       Run only API tests"
    Write-Host "  -IdeOnly       Run only IDE integration tests"
    Write-Host ""
    Write-Host "Environment Variables:"
    Write-Host "  SKIP_LARGE_MODELS=true  Skip 15B model tests (for systems with limited VRAM)"
    Write-Host ""
}

function Start-MainExecution {
    Write-Host "Project Root: $(Get-Location)"
    Write-Host ""
    
    # Phase 1: Prerequisites
    if (-not (Test-Prerequisites)) {
        Write-Error "Prerequisites check failed - aborting tests"
        exit 1
    }
    
    # Phase 2: Environment Setup
    Initialize-TestEnvironment
    
    # Phase 3: Configuration Tests
    Write-Info "Phase 3: Configuration Validation"
    $configResult = Invoke-TestSuite "Configuration Validation" "tests/e2e/configuration-validation.spec.ts" 120
    
    # Phase 4: API Tests
    Write-Info "Phase 4: API Validation"
    $apiResult = Invoke-TestSuite "API Validation" "tests/e2e/api-validation.spec.ts" 600
    
    # Phase 5: IDE Integration Tests  
    Write-Info "Phase 5: IDE Integration"
    $ideResult = Invoke-TestSuite "IDE Integration" "tests/e2e/ide-integration.spec.ts" 600
    
    # Generate comprehensive report
    New-TestReport
    
    # Final summary
    Write-Host ""
    Write-Host "🏁 Test Execution Complete" -ForegroundColor Blue
    Write-Host "==========================" -ForegroundColor Blue
    Write-Host ""
    
    if ($script:TestsFailed -eq 0) {
        Write-Success "All test suites passed! ($script:TestsPassed/$($script:TestsPassed + $script:TestsFailed))"
        Write-Host ""
        Write-Host "🎉 Your vLLM-Doctrine installation is fully validated!" -ForegroundColor Green
        Write-Host "   You can safely use this system for local LLM serving."
        Write-Host ""
        Write-Host "📋 Next steps:"
        Write-Host "   1. Configure your IDE to connect to http://localhost:<port>/v1"
        Write-Host "   2. Launch models with ./daily-bootstrap.sh {fast|edit|qa|plan}"
        Write-Host "   3. Test connections with ./test-connection.sh <port>"
        exit 0
    } else {
        Write-Error "Some test suites failed ($script:TestsFailed/$($script:TestsPassed + $script:TestsFailed))"
        Write-Host ""
        Write-Host "🔍 Check the following:" -ForegroundColor Yellow
        Write-Host "   1. Run ./initial-bootstrap.sh to ensure complete setup"
        Write-Host "   2. Verify HuggingFace authentication: huggingface-cli whoami"
        Write-Host "   3. Check GPU availability: nvidia-smi"
        Write-Host "   4. Review test report: test-results/comprehensive-test-report.md"
        Write-Host "   5. Check individual test logs in test-results/ directory"
        exit 1
    }
}

# Main execution logic
if ($Help) {
    Show-Help
} elseif ($ConfigOnly) {
    Test-Prerequisites
    Initialize-TestEnvironment
    Invoke-TestSuite "Configuration Validation" "tests/e2e/configuration-validation.spec.ts" 120
    New-TestReport
} elseif ($ApiOnly) {
    Test-Prerequisites
    Initialize-TestEnvironment
    Invoke-TestSuite "API Validation" "tests/e2e/api-validation.spec.ts" 600
    New-TestReport
} elseif ($IdeOnly) {
    Test-Prerequisites
    Initialize-TestEnvironment
    Invoke-TestSuite "IDE Integration" "tests/e2e/ide-integration.spec.ts" 600
    New-TestReport
} else {
    Start-MainExecution
}