#!/usr/bin/env bash
# -------------------------------------------------------------------
# vLLM-Doctrine Comprehensive Test Runner
# 
# This script orchestrates the complete testing suite for validating
# the vLLM-Doctrine system across all model tiers and scenarios.
# -------------------------------------------------------------------

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

echo "🧪 vLLM-Doctrine Comprehensive Test Suite"
echo "=========================================="
echo ""

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Test results tracking
TESTS_PASSED=0
TESTS_FAILED=0
TEST_RESULTS=()

log_info() {
    echo -e "${BLUE}ℹ️  $1${NC}"
}

log_success() {
    echo -e "${GREEN}✅ $1${NC}"
    TESTS_PASSED=$((TESTS_PASSED + 1))
    TEST_RESULTS+=("✅ $1")
}

log_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

log_error() {
    echo -e "${RED}❌ $1${NC}"
    TESTS_FAILED=$((TESTS_FAILED + 1))
    TEST_RESULTS+=("❌ $1")
}

# Function to run a test suite
run_test_suite() {
    local suite_name="$1"
    local test_file="$2"
    local timeout="${3:-300}" # 5 minute default timeout
    
    log_info "Running $suite_name..."
    
    if timeout "${timeout}s" npx playwright test "$test_file" --reporter=line; then
        log_success "$suite_name completed"
        return 0
    else
        local exit_code=$?
        if [ $exit_code -eq 124 ]; then
            log_error "$suite_name timed out after ${timeout} seconds"
        else
            log_error "$suite_name failed with exit code $exit_code"
        fi
        return $exit_code
    fi
}

# Function to check prerequisites
check_prerequisites() {
    log_info "Checking prerequisites..."
    
    # Check if we're in the right directory
    if [ ! -f "./initial-bootstrap.sh" ]; then
        log_error "Not in vLLM-Doctrine directory or setup incomplete"
        return 1
    fi
    
    # Check Node.js and npm
    if ! command -v node &> /dev/null; then
        log_error "Node.js is required but not installed"
        return 1
    fi
    
    if ! command -v npm &> /dev/null; then
        log_error "npm is required but not installed" 
        return 1
    fi
    
    # Install dependencies if needed
    if [ ! -d "node_modules" ]; then
        log_info "Installing test dependencies..."
        npm install
    fi
    
    # Install Playwright browsers if needed
    if [ ! -d "node_modules/@playwright" ]; then
        log_error "Playwright not installed - run 'npm install' first"
        return 1
    fi
    
    # Check Python environment
    if [ ! -d ~/torch-env ]; then
        log_warning "Python virtual environment not found at ~/torch-env"
        log_warning "Run ./initial-bootstrap.sh to set up the environment"
    fi
    
    log_success "Prerequisites check completed"
    return 0
}

# Function to setup test environment
setup_test_environment() {
    log_info "Setting up test environment..."
    
    # Create test results directory
    mkdir -p test-results
    
    # Stop any running models
    pkill -f "vllm.entrypoints.openai.api_server" 2>/dev/null || true
    
    # Wait for cleanup
    sleep 2
    
    log_success "Test environment ready"
}

# Function to generate test report
generate_test_report() {
    local report_file="test-results/comprehensive-test-report.md"
    
    cat > "$report_file" << EOF
# vLLM-Doctrine Comprehensive Test Report

**Generated:** $(date)
**Total Tests:** $((TESTS_PASSED + TESTS_FAILED))
**Passed:** $TESTS_PASSED
**Failed:** $TESTS_FAILED
**Success Rate:** $(( TESTS_PASSED * 100 / (TESTS_PASSED + TESTS_FAILED) ))%

## Test Results

EOF

    for result in "${TEST_RESULTS[@]}"; do
        echo "$result" >> "$report_file"
    done
    
    cat >> "$report_file" << EOF

## Environment Information

- **OS:** $(uname -s)
- **Date:** $(date)
- **Node.js:** $(node --version 2>/dev/null || echo "Not available")
- **Python:** $(python3 --version 2>/dev/null || echo "Not available")
- **GPU:** $(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null || echo "Not detected")

## Notes

This report was generated by the vLLM-Doctrine comprehensive test suite.
For detailed test outputs, check the individual test result files in the test-results directory.
EOF

    log_success "Test report generated: $report_file"
}

# Main test execution
main() {
    cd "$PROJECT_ROOT"
    
    echo "Project Root: $PROJECT_ROOT"
    echo "Test Directory: $SCRIPT_DIR"
    echo ""
    
    # Phase 1: Prerequisites
    if ! check_prerequisites; then
        log_error "Prerequisites check failed - aborting tests"
        exit 1
    fi
    
    # Phase 2: Environment Setup
    setup_test_environment
    
    # Phase 3: Configuration Tests (fast, no models needed)
    log_info "Phase 3: Configuration Validation"
    run_test_suite "Configuration Validation" "tests/e2e/configuration-validation.spec.ts" 120
    
    # Phase 4: API Tests (requires model launching)
    log_info "Phase 4: API Validation" 
    run_test_suite "API Validation" "tests/e2e/api-validation.spec.ts" 600 # 10 minutes
    
    # Phase 5: IDE Integration Tests
    log_info "Phase 5: IDE Integration"
    run_test_suite "IDE Integration" "tests/e2e/ide-integration.spec.ts" 600
    
    # Phase 6: Cleanup and Reporting
    log_info "Cleaning up test environment..."
    pkill -f "vllm.entrypoints.openai.api_server" 2>/dev/null || true
    
    # Generate comprehensive report
    generate_test_report
    
    # Final summary
    echo ""
    echo "🏁 Test Execution Complete"
    echo "=========================="
    echo ""
    
    if [ $TESTS_FAILED -eq 0 ]; then
        log_success "All test suites passed! ($TESTS_PASSED/$((TESTS_PASSED + TESTS_FAILED)))"
        echo ""
        echo "🎉 Your vLLM-Doctrine installation is fully validated!"
        echo "   You can safely use this system for local LLM serving."
        echo ""
        echo "📋 Next steps:"
        echo "   1. Configure your IDE to connect to http://localhost:<port>/v1"
        echo "   2. Launch models with ./daily-bootstrap.sh {fast|edit|qa|plan}"
        echo "   3. Test connections with ./test-connection.sh <port>"
        exit 0
    else
        log_error "Some test suites failed ($TESTS_FAILED/$((TESTS_PASSED + TESTS_FAILED)))"
        echo ""
        echo "🔍 Check the following:"
        echo "   1. Run ./initial-bootstrap.sh to ensure complete setup"
        echo "   2. Verify HuggingFace authentication: huggingface-cli whoami"
        echo "   3. Check GPU availability: nvidia-smi"
        echo "   4. Review test report: test-results/comprehensive-test-report.md"
        echo "   5. Check individual test logs in test-results/ directory"
        exit 1
    fi
}

# Handle script arguments
case "${1:-}" in
    --help|-h)
        echo "vLLM-Doctrine Comprehensive Test Runner"
        echo ""
        echo "Usage: $0 [options]"
        echo ""
        echo "Options:"
        echo "  --help, -h     Show this help message"
        echo "  --config-only  Run only configuration tests"
        echo "  --api-only     Run only API tests"
        echo "  --ide-only     Run only IDE integration tests"
        echo ""
        echo "Environment Variables:"
        echo "  SKIP_LARGE_MODELS=true  Skip 15B model tests (for systems with limited VRAM)"
        echo ""
        exit 0
        ;;
    --config-only)
        check_prerequisites
        setup_test_environment
        run_test_suite "Configuration Validation" "tests/e2e/configuration-validation.spec.ts" 120
        generate_test_report
        ;;
    --api-only)
        check_prerequisites
        setup_test_environment
        run_test_suite "API Validation" "tests/e2e/api-validation.spec.ts" 600
        generate_test_report
        ;;
    --ide-only)
        check_prerequisites
        setup_test_environment
        run_test_suite "IDE Integration" "tests/e2e/ide-integration.spec.ts" 600
        generate_test_report
        ;;
    *)
        main "$@"
        ;;
esac