#!/bin/bash

################################################################################
# vLLM-Doctrine Setup Verification Script
# 
# PURPOSE: Validates that initial-bootstrap.sh completed successfully and all
#          helper scripts were generated correctly
#
# USAGE: ./verify-setup.sh
#        or: ./verify-setup.sh --verbose
#
# EXIT CODES:
#   0 = All checks passed
#   1 = One or more checks failed
#
################################################################################

set -eu

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

VERBOSE=false
if [[ "$1" == "--verbose" ]]; then
    VERBOSE=true
fi

# Counter for checks
CHECKS_PASSED=0
CHECKS_FAILED=0

# Helper functions
check_start() {
    local name="$1"
    printf "%-50s" "Checking: $name..."
    if [[ "$VERBOSE" == "true" ]]; then
        echo ""
    fi
}

check_pass() {
    if [[ "$VERBOSE" == "false" ]]; then
        echo -e "${GREEN}✅ PASS${NC}"
    else
        echo -e "  ${GREEN}✅ PASS${NC}"
    fi
    ((CHECKS_PASSED++))
}

check_fail() {
    local msg="$1"
    if [[ "$VERBOSE" == "false" ]]; then
        echo -e "${RED}❌ FAIL${NC}"
    else
        echo -e "  ${RED}❌ FAIL${NC}"
    fi
    echo -e "    ${RED}Error: $msg${NC}"
    ((CHECKS_FAILED++))
}

check_warn() {
    local msg="$1"
    echo -e "    ${YELLOW}⚠️  Warning: $msg${NC}"
}

# Print header
echo -e "${BLUE}╔════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║   vLLM-Doctrine Setup Verification Script              ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════╝${NC}"
echo ""

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOCTRINE_DIR="$(dirname "$SCRIPT_DIR")"

if [[ "$VERBOSE" == "true" ]]; then
    echo "Doctrine directory: $DOCTRINE_DIR"
    echo ""
fi

# ============================================================================
# CHECK 1: Python Environment
# ============================================================================
check_start "Python virtual environment at ~/torch-env"
if [[ -d "$HOME/torch-env" ]]; then
    check_pass
else
    check_fail "Python virtual environment not found at ~/torch-env"
fi

# ============================================================================
# CHECK 2: Configuration Files
# ============================================================================
check_start "models.conf configuration file"
if [[ -f "$DOCTRINE_DIR/models.conf" ]]; then
    check_pass
else
    check_fail "models.conf not found in $DOCTRINE_DIR"
fi

check_start "ports.conf configuration file"
if [[ -f "$DOCTRINE_DIR/ports.conf" ]]; then
    check_pass
else
    check_fail "ports.conf not found in $DOCTRINE_DIR"
fi

# ============================================================================
# CHECK 3: Helper Scripts (Generated by initial-bootstrap.sh)
# ============================================================================
check_start "daily-bootstrap.sh script"
if [[ -f "$DOCTRINE_DIR/daily-bootstrap.sh" ]]; then
    if [[ -x "$DOCTRINE_DIR/daily-bootstrap.sh" ]]; then
        check_pass
    else
        check_warn "daily-bootstrap.sh exists but is not executable (fixing...)"
        chmod +x "$DOCTRINE_DIR/daily-bootstrap.sh"
        check_pass
    fi
else
    check_fail "daily-bootstrap.sh not found - did you run initial-bootstrap.sh?"
fi

check_start "test-connection.sh script"
if [[ -f "$DOCTRINE_DIR/test-connection.sh" ]]; then
    if [[ -x "$DOCTRINE_DIR/test-connection.sh" ]]; then
        check_pass
    else
        check_warn "test-connection.sh exists but is not executable (fixing...)"
        chmod +x "$DOCTRINE_DIR/test-connection.sh"
        check_pass
    fi
else
    check_fail "test-connection.sh not found - did you run initial-bootstrap.sh?"
fi

# ============================================================================
# CHECK 4: HuggingFace Authentication
# ============================================================================
check_start "HuggingFace authentication"
if [[ -f "$HOME/.cache/huggingface/token" ]]; then
    check_pass
else
    check_warn "HuggingFace token not found - some models may require manual authentication"
    ((CHECKS_PASSED++))  # Don't count as failure, just a warning
fi

# ============================================================================
# CHECK 5: GPU/CUDA (optional but recommended)
# ============================================================================
check_start "NVIDIA GPU and CUDA support"
if command -v nvidia-smi &> /dev/null; then
    check_pass
    if [[ "$VERBOSE" == "true" ]]; then
        nvidia-smi --query-gpu=name,memory.total --format=csv,noheader | while read -r line; do
            echo "    GPU: $line"
        done
    fi
else
    check_warn "NVIDIA GPU not detected - CPU mode will be slow but functional"
    ((CHECKS_PASSED++))  # Don't count as failure
fi

# ============================================================================
# CHECK 6: PyTorch Installation
# ============================================================================
check_start "PyTorch installation"
if source "$HOME/torch-env/bin/activate" 2>/dev/null && \
   python -c "import torch; print(torch.__version__)" &>/dev/null; then
    if [[ "$VERBOSE" == "true" ]]; then
        TORCH_VERSION=$(python -c "import torch; print(torch.__version__)")
        echo "    PyTorch version: $TORCH_VERSION"
    fi
    check_pass
else
    check_fail "PyTorch not found in virtual environment"
fi

# ============================================================================
# CHECK 7: vLLM Installation
# ============================================================================
check_start "vLLM installation"
if source "$HOME/torch-env/bin/activate" 2>/dev/null && \
   python -c "import vllm; print(vllm.__version__)" &>/dev/null; then
    if [[ "$VERBOSE" == "true" ]]; then
        VLLM_VERSION=$(python -c "import vllm; print(vllm.__version__)")
        echo "    vLLM version: $VLLM_VERSION"
    fi
    check_pass
else
    check_fail "vLLM not found in virtual environment"
fi

# ============================================================================
# SUMMARY
# ============================================================================
echo ""
echo -e "${BLUE}╔════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║                      SUMMARY                           ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════╝${NC}"

TOTAL=$((CHECKS_PASSED + CHECKS_FAILED))
echo -e "Total checks: $TOTAL"
echo -e "  ${GREEN}✅ Passed: $CHECKS_PASSED${NC}"
if [[ $CHECKS_FAILED -gt 0 ]]; then
    echo -e "  ${RED}❌ Failed: $CHECKS_FAILED${NC}"
else
    echo -e "  ${RED}❌ Failed: $CHECKS_FAILED${NC}"
fi

echo ""
if [[ $CHECKS_FAILED -eq 0 ]]; then
    echo -e "${GREEN}✨ All checks passed! Your setup is ready.${NC}"
    echo ""
    echo "🚀 Next steps:"
    echo "  1. Launch a model:  cd ~/.config/llm-doctrine && ./daily-bootstrap.sh qa"
    echo "  2. Test connection: ./test-connection.sh 8500"
    echo "  3. Chat with curl:  curl http://localhost:8500/v1/chat/completions ..."
    echo ""
    exit 0
else
    echo -e "${RED}❌ Some checks failed. Review the errors above.${NC}"
    echo ""
    echo "💡 Troubleshooting:"
    echo "  - Re-run initial-bootstrap.sh: ./scripts/initial-bootstrap.sh"
    echo "  - Check permissions: chmod +x scripts/*.sh"
    echo "  - View detailed logs: cat ~/.vllm-doctrine/setup.log (if available)"
    echo ""
    exit 1
fi